using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace ParallelQA
{
    /// <summary>
    /// Independent Wave B RED-first contract. Acceptance comes from public
    /// stable IDs, derived finite stock, canonical generated bytes, fresh
    /// snapshots, and a live Play-scene trace. Product bool assertions,
    /// fixture-only probes, implementation class names, grant, warp, and skip
    /// are deliberately not acceptance evidence.
    /// </summary>
    public static class GameJamWaveBRedFirstGateRunner
    {
        private const string RedBaseline = "00e0d5a9df597ab4a9f54bff665291f367d40c92";
        private const string ScenePath = "Assets/_Project/Scenes/KimSurvivalPrototype.unity";
        private const string PlayRunningKey = "ParallelQA.GameJamWaveB.PlayRunning";
        private const string PlayExitPassKey = "ParallelQA.GameJamWaveB.PlayExitPass";
        private const string PlayMessageKey = "ParallelQA.GameJamWaveB.PlayMessage";
        private const int ExpectedRegionCount = 7;
        private const int ExpectedArchetypeCount = 21;
        private const int ExpectedInstanceCount = 42;
        private const int ExpectedGeneralUnits = 144;
        private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(false);
        private static readonly BindingFlags PublicInstance = BindingFlags.Instance | BindingFlags.Public;
        private static readonly BindingFlags PublicStatic = BindingFlags.Static | BindingFlags.Public;
        private static readonly string[] ExpectedRegionIds =
        {
            "region.coast.beach",
            "region.sea.shallows",
            "region.forest.grove",
            "region.ridge.highland",
            "region.cave.island",
            "region.cove.wreck",
            "region.ruins.relay"
        };
        private static bool playTickAttached;
        private static double playEarliestRunTime;
        private static double playTimeoutAt;

        [Serializable]
        private sealed class Check
        {
            public string id;
            public string matrix;
            public string status;
            public string classification;
            public string severity;
            public string expected;
            public string actual;
            public string reproduction;
            public string recommendedFiles;
        }

        [Serializable]
        private sealed class Report
        {
            public int schemaVersion = 1;
            public string title;
            public string runId;
            public string baselineCommit;
            public string unityVersion;
            public string startedUtc;
            public string completedUtc;
            public string overall;
            public string productOverall;
            public string infrastructureOverall;
            public int passed;
            public int expectedGaps;
            public int productFailed;
            public int infrastructureFailed;
            public int unverified;
            public int notReady;
            public string greenCompletionCondition;
            public string physicalGamepad = "UNVERIFIED";
            public string steamReadiness = "NOT_READY";
            public Check[] checks;
        }

        [Serializable]
        private sealed class CatalogEvidence
        {
            public string owner = string.Empty;
            public string[] regionIds = Array.Empty<string>();
            public string[] archetypeIds = Array.Empty<string>();
            public string[] instanceIds = Array.Empty<string>();
            public string[] legacyNodeIds = Array.Empty<string>();
            public int finiteGeneralResourceUnits;
            public int finiteResourceEntryCount;
            public string[] finiteResourceSources = Array.Empty<string>();
        }

        [Serializable]
        private sealed class GenerationEvidence
        {
            public string owner = string.Empty;
            public string methodSurface = string.Empty;
            public bool sameSeedRevisionByteEqual;
            public bool differentSeedVaries;
            public bool stableIdsPreservedAcrossSeeds;
            public bool revisionsStored;
            public string firstSha256 = string.Empty;
            public string repeatSha256 = string.Empty;
            public string alternateSha256 = string.Empty;
            public string error = string.Empty;
        }

        [Serializable]
        private sealed class EditEvidence
        {
            public string runId;
            public string baselineCommit;
            public string discoveryPolicy;
            public CatalogEvidence catalog;
            public GenerationEvidence generation;
            public string persistenceSurface;
            public bool contractRevisionStored;
            public bool lootTableRevisionStored;
            public bool newGameOnlyStockSurface;
            public string localizationDetail;
        }

        [Serializable]
        private sealed class LayoutEvidence
        {
            public string locale = string.Empty;
            public string screenshot = string.Empty;
            public int screenWidth;
            public int screenHeight;
            public int overflowCount;
            public int offscreenCount;
            public bool playerClear;
            public bool walkingBandClear;
            public string result = "FAIL";
            public string failureReason = string.Empty;
        }

        [Serializable]
        private sealed class PlayEvidence
        {
            public string runId;
            public string baselineCommit;
            public string scene;
            public string discoveryPolicy;
            public string searchEvidenceSource;
            public string liveObservationOwner;
            public string liveObservationMethod;
            public string liveObservationSurface;
            public string observationError;
            public string[] searchStateSequence = Array.Empty<string>();
            public string[] searchInteractionTrace = Array.Empty<string>();
            public string knownRemainingFingerprint;
            public bool searchGrant;
            public bool searchWarp;
            public bool searchSkip;
            public string[] stockFingerprints = Array.Empty<string>();
            public string[] stockGenerationEvents = Array.Empty<string>();
            public string diseaseId;
            public string[] diseasePhaseSequence = Array.Empty<string>();
            public string[] diseaseInteractionTrace = Array.Empty<string>();
            public string[] diseaseStateFingerprints = Array.Empty<string>();
            public int exposureApplyCount = -1;
            public int effectApplyCount = -1;
            public int worsenApplyCount = -1;
            public int treatmentCostCount = -1;
            public int duplicateCostDelta = int.MinValue;
            public int duplicateHazardDelta = int.MinValue;
            public int cancelContaminationDelta = int.MinValue;
            public bool grant;
            public bool warp;
            public bool skip;
            public bool cheatFieldsObserved;
            public string keyboardMeaning;
            public string gamepadMeaning;
            public string[] localeStateFingerprints = Array.Empty<string>();
            public LayoutEvidence[] layouts = Array.Empty<LayoutEvidence>();
            public string[] joystickNames = Array.Empty<string>();
        }

        [Serializable]
        private sealed class FreshSearchEvidence
        {
            public string[] stateSequence;
            public string[] interactionTrace;
            public string remainingItemsFingerprint;
            public bool grant;
            public bool warp;
            public bool skip;
        }

        private sealed class CatalogCandidate
        {
            public string Owner = string.Empty;
            public readonly HashSet<string> RegionIds = new HashSet<string>(StringComparer.Ordinal);
            public readonly HashSet<string> ArchetypeIds = new HashSet<string>(StringComparer.Ordinal);
            public readonly HashSet<string> InstanceIds = new HashSet<string>(StringComparer.Ordinal);
            public readonly HashSet<string> LegacyNodeIds = new HashSet<string>(StringComparer.Ordinal);
            public readonly List<ResourceBucket> ResourceBuckets = new List<ResourceBucket>();
            public int LootUnits;
            public int LootEntries;
        }

        private sealed class ResourceBucket
        {
            public string Path = string.Empty;
            public int Units;
            public int Entries;
        }

        private sealed class ReferenceComparer : IEqualityComparer<object>
        {
            public new bool Equals(object left, object right) { return ReferenceEquals(left, right); }
            public int GetHashCode(object value) { return System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(value); }
        }

        private static string RunId
        {
            get
            {
                string value = Environment.GetEnvironmentVariable("KIM_PARALLEL_QA_RUN_ID");
                return string.IsNullOrWhiteSpace(value) ? "wave-b-missing-run-id" : Sanitize(value);
            }
        }

        private static string BaselineCommit
        {
            get
            {
                string value = Environment.GetEnvironmentVariable("KIM_PARALLEL_QA_BASELINE");
                return string.IsNullOrWhiteSpace(value) ? RedBaseline : value.Trim();
            }
        }

        private static bool IsRedBaseline
        {
            get { return string.Equals(BaselineCommit, RedBaseline, StringComparison.OrdinalIgnoreCase); }
        }

        private static string EvidenceFolder
        {
            get { return Path.GetFullPath(Path.Combine(Application.dataPath, "..", "Artifacts", "ParallelQA", RunId)); }
        }

        public static void RunEditContracts()
        {
            DateTime started = DateTime.UtcNow;
            Directory.CreateDirectory(EvidenceFolder);
            List<Check> checks = new List<Check>();
            Assembly runtime = typeof(KimSurvival.GameSession).Assembly;
            CatalogEvidence catalog = DiscoverCatalog(runtime);
            GenerationEvidence generation = DiscoverGeneration(runtime);
            string persistenceSurface = DiscoverPersistenceSurface(runtime);
            string lowerSurface = persistenceSurface.ToLowerInvariant();
            bool contractRevisionStored = lowerSurface.Contains("contractrevision");
            bool lootTableRevisionStored = lowerSurface.Contains("loottablerevision");
            bool newGameOnlyStockSurface = lowerSurface.Contains("newgame") &&
                                           lowerSurface.Contains("stock") &&
                                           (lowerSurface.Contains("generation") || lowerSurface.Contains("initialize"));
            string localizationDetail = AuditLocalization(out bool localizationPass);

            Infrastructure(checks, "GWB-I01.exact_baseline", "Edit infrastructure", "P0",
                "Fresh RunId and exact full baseline SHA are recorded",
                delegate
                {
                    Require(RunId != "wave-b-missing-run-id", "KIM_PARALLEL_QA_RUN_ID is missing");
                    Require(BaselineCommit.Length == 40, "baseline is not a full SHA: " + BaselineCommit);
                    return "runId=" + RunId + "; baseline=" + BaselineCommit + "; redBaseline=" + IsRedBaseline;
                },
                "Run the single PowerShell entry point at the exact requested HEAD with a fresh RunId.",
                "Assets/Editor/ParallelQA/Invoke-GameJamWaveBRedFirstGate.ps1");

            Product(checks, "GWB-E01.catalog_7_21_42_144", "finite catalog", "P0",
                "Exactly 7 canonical region IDs, 21 node.archetype IDs, 42 node.instance IDs, and 144 derived general resource units load from one public structured catalog",
                delegate
                {
                    bool regionsPass = catalog.regionIds.SequenceEqual(ExpectedRegionIds.OrderBy(value => value, StringComparer.Ordinal));
                    bool catalogPass = regionsPass && catalog.archetypeIds.Length == ExpectedArchetypeCount &&
                                       catalog.instanceIds.Length == ExpectedInstanceCount &&
                                       catalog.finiteGeneralResourceUnits == ExpectedGeneralUnits;
                    Require(catalogPass, DescribeCatalog(catalog) + "; expected=7/21/42/144");
                    return DescribeCatalog(catalog);
                },
                "Enumerate public structured catalogs, collect stable IDs, and derive units from resource amount entries rather than a bool assertion.",
                "runtime Wave B catalog owner selected by public stable-ID and resource-entry shape");

            Product(checks, "GWB-E02.seed_revision_byte_determinism", "generation determinism", "P0",
                "The public new-run generator emits byte-equal output for the same seed+revisions, valid stock variation for another seed, and identical stable IDs",
                delegate
                {
                    Require(!string.IsNullOrWhiteSpace(generation.owner), "no public structured seed+revision generator was discovered: " + generation.error);
                    Require(generation.sameSeedRevisionByteEqual, "same seed+revision bytes differ");
                    Require(generation.differentSeedVaries, "different seed produced no valid stock/placement variation");
                    Require(generation.stableIdsPreservedAcrossSeeds, "changing seed changed stable IDs");
                    Require(generation.revisionsStored, "generated output does not store contractRevision and lootTableRevision");
                    return generation.owner + "; sha=" + generation.firstSha256 + "/" + generation.repeatSha256 +
                           "; alternate=" + generation.alternateSha256;
                },
                "Invoke a public structured generator twice with one seed/revision and once with another seed, then canonicalize and compare UTF-8 bytes.",
                "runtime new-run generation owner selected by parameter and returned-data shape");

            Product(checks, "GWB-E03.revision_and_new_game_stock_schema", "run persistence schema", "P0",
                "Run state stores contractRevision and lootTableRevision and exposes stock generation as a new-game-only transition",
                delegate
                {
                    Require(contractRevisionStored && lootTableRevisionStored && newGameOnlyStockSurface,
                        "contractRevision/lootTableRevision/newGameStock=" + contractRevisionStored + "/" +
                        lootTableRevisionStored + "/" + newGameOnlyStockSurface + "; surface=" + persistenceSurface);
                    return persistenceSurface;
                },
                "Inspect public snapshot and transition member surfaces; a text fixture or pass flag is not accepted.",
                "runtime run snapshot and new-game generation transition owners selected by structured surface");

            Product(checks, "GWB-E04.ko_en_qps_wave_b_surface", "localization data", "P1",
                "ko/en/qps-long canonical rows cover known remainder, broken barrier, removed hazard, and disease telegraph/exposure/effect/worsen/mitigate-or-treat semantics",
                delegate
                {
                    Require(localizationPass, localizationDetail);
                    return localizationDetail;
                },
                "Parse the canonical localization TSV and require non-empty locale-owned rows for every Wave B semantic group.",
                "Assets/_Project/Scripts/Localization/PrototypeStrings.tsv");

            WriteJson("gamejam-wave-b-edit-observation-evidence.json", new EditEvidence
            {
                runId = RunId,
                baselineCommit = BaselineCommit,
                discoveryPolicy = "Public structured stable IDs, derived resource amounts, and generated canonical bytes. Class-name allowlists, bool assertions, and fixture strings are rejected.",
                catalog = catalog,
                generation = generation,
                persistenceSurface = persistenceSurface,
                contractRevisionStored = contractRevisionStored,
                lootTableRevisionStored = lootTableRevisionStored,
                newGameOnlyStockSurface = newGameOnlyStockSurface,
                localizationDetail = localizationDetail
            });
            WriteReport("gamejam-wave-b-edit-contracts", "GameJam Wave B RED-first Edit contracts", started, checks);
        }

        public static void RunPlayContracts()
        {
            Directory.CreateDirectory(EvidenceFolder);
            SessionState.SetBool(PlayRunningKey, true);
            SessionState.SetBool(PlayExitPassKey, false);
            SessionState.SetString(PlayMessageKey, "GameJam Wave B Play runner did not complete");
            EditorSceneManager.OpenScene(ScenePath, OpenSceneMode.Single);
            AttachPlayCallbacks();
            EditorApplication.isPlaying = true;
        }

        [InitializeOnLoadMethod]
        private static void ResumePlayContracts()
        {
            if (SessionState.GetBool(PlayRunningKey, false)) AttachPlayCallbacks();
        }

        private static void AttachPlayCallbacks()
        {
            EditorApplication.playModeStateChanged -= OnPlayModeStateChanged;
            EditorApplication.playModeStateChanged += OnPlayModeStateChanged;
            if (!EditorApplication.isPlaying) return;
            playEarliestRunTime = EditorApplication.timeSinceStartup + 1.5d;
            playTimeoutAt = EditorApplication.timeSinceStartup + 240d;
            if (!playTickAttached) { EditorApplication.update += PlayTick; playTickAttached = true; }
        }

        private static void OnPlayModeStateChanged(PlayModeStateChange state)
        {
            if (state == PlayModeStateChange.EnteredPlayMode)
            {
                playEarliestRunTime = EditorApplication.timeSinceStartup + 1.5d;
                playTimeoutAt = EditorApplication.timeSinceStartup + 240d;
                if (!playTickAttached) { EditorApplication.update += PlayTick; playTickAttached = true; }
            }
            else if (state == PlayModeStateChange.EnteredEditMode) FinishPlayContracts();
        }

        private static void PlayTick()
        {
            if (!EditorApplication.isPlaying) return;
            if (EditorApplication.timeSinceStartup > playTimeoutAt)
            {
                WritePlayInfrastructureFailure(new TimeoutException("GameJam Wave B Play runner timed out."));
                StopPlayContracts();
                return;
            }
            if (EditorApplication.timeSinceStartup < playEarliestRunTime) return;
            if (playTickAttached) { EditorApplication.update -= PlayTick; playTickAttached = false; }

            try
            {
                DateTime started = DateTime.UtcNow;
                PlayEvidence evidence = ObservePlay();
                List<Check> checks = new List<Check>();

                Product(checks, "GWB-P01.return_forced_return_snapshot_persistence", "actual persistence trace", "P0",
                    "Actual Play trace preserves hidden/partial/depleted, known remainder, broken barrier, and removed persistent hazard through return, forced return, revisit, and snapshot restore",
                    delegate
                    {
                        Require(SequenceHas(evidence.searchStateSequence, "hidden", "partial", "depleted"),
                            "state sequence=" + string.Join(">", evidence.searchStateSequence));
                        Require(!string.IsNullOrWhiteSpace(evidence.knownRemainingFingerprint), "known remaining fingerprint is missing");
                        Require(TraceHas(evidence.searchInteractionTrace, "return") &&
                                TraceHas(evidence.searchInteractionTrace, "forced", "return") &&
                                TraceHas(evidence.searchInteractionTrace, "revisit") &&
                                TraceHas(evidence.searchInteractionTrace, "snapshot", "restore") &&
                                TraceHas(evidence.searchInteractionTrace, "barrier", "broken") &&
                                TraceHas(evidence.searchInteractionTrace, "hazard", "removed"),
                            "required transitions are absent: " + string.Join(" | ", evidence.searchInteractionTrace));
                        Require(!evidence.searchGrant && !evidence.searchWarp && !evidence.searchSkip,
                            "search trace contains grant/warp/skip");
                        return "source=" + evidence.searchEvidenceSource + "; trace=" + string.Join(" | ", evidence.searchInteractionTrace);
                    },
                    "Use a fresh run, naturally search, return, force-return, revisit, serialize, restore, and compare stable state fingerprints.",
                    "runtime region/search persistence owners selected by live trace and public snapshot");

                Product(checks, "GWB-P02.stock_not_regenerated_outside_new_game", "stock lifecycle", "P0",
                    "The same seed+revisions keeps byte-identical stock across transition/return/forced-return/revisit/restore; stock generation occurs only once at new game",
                    delegate
                    {
                        Require(evidence.stockFingerprints.Length >= 5,
                            "stock fingerprints missing: " + string.Join(",", evidence.stockFingerprints));
                        Require(evidence.stockFingerprints.Distinct(StringComparer.Ordinal).Count() == 1,
                            "stock regenerated outside new game: " + string.Join(",", evidence.stockFingerprints));
                        Require(evidence.stockGenerationEvents.Length == 1 &&
                                evidence.stockGenerationEvents[0].IndexOf("new", StringComparison.OrdinalIgnoreCase) >= 0,
                            "stock generation events=" + string.Join(",", evidence.stockGenerationEvents));
                        return "fingerprints=" + string.Join(",", evidence.stockFingerprints) +
                               "; generation=" + string.Join(",", evidence.stockGenerationEvents);
                    },
                    "Observe generation event and stock bytes across every non-new-game transition without reopening or reconstructing fixtures.",
                    "runtime new-game stock and run snapshot owners selected by structured live observation");

                Product(checks, "GWB-P03.natural_disease_lifecycle_atomic", "natural disease lifecycle", "P0",
                    "One actual disease trace proceeds telegraph→exposure→effect→worsen→mitigate/treat with single application and zero duplicate/cancel contamination",
                    delegate
                    {
                        Require(IsStableDiseaseId(evidence.diseaseId), "stable disease ID missing: " + evidence.diseaseId);
                        Require(DiseaseSequencePasses(evidence.diseasePhaseSequence),
                            "disease phases=" + string.Join(">", evidence.diseasePhaseSequence));
                        Require(DiseaseSequencePasses(evidence.diseaseInteractionTrace),
                            "disease interaction trace lacks ordered phases: " + string.Join(" | ", evidence.diseaseInteractionTrace));
                        Require(evidence.diseaseStateFingerprints.Length >= 5 &&
                                evidence.diseaseStateFingerprints.Distinct(StringComparer.Ordinal).Count() >= 4,
                            "structured state fingerprints missing or static: " + string.Join(",", evidence.diseaseStateFingerprints));
                        Require(evidence.exposureApplyCount == 1 && evidence.effectApplyCount == 1 &&
                                evidence.worsenApplyCount == 1 && evidence.treatmentCostCount == 1,
                            "application counts exposure/effect/worsen/treat=" + evidence.exposureApplyCount + "/" +
                            evidence.effectApplyCount + "/" + evidence.worsenApplyCount + "/" + evidence.treatmentCostCount);
                        Require(evidence.duplicateCostDelta == 0 && evidence.duplicateHazardDelta == 0 && evidence.cancelContaminationDelta == 0,
                            "duplicateCost/duplicateHazard/cancelContamination=" + evidence.duplicateCostDelta + "/" +
                            evidence.duplicateHazardDelta + "/" + evidence.cancelContaminationDelta);
                        return DescribeDisease(evidence);
                    },
                    "From a fresh run, walk to a declared disease region and complete exposure, worsening, and mitigation/treatment through actual interactions.",
                    "runtime live disease state, treatment transaction, and hazard ledger owners selected by structured trace");

                Product(checks, "GWB-P04.ko_en_qps_input_layout_parity", "locale/input/layout", "P1",
                    "ko/en/qps-long actual 1280x800 disease/search states have zero overflow/offscreen/occlusion and keyboard/mouse plus synthetic gamepad preserve identical meaning",
                    delegate
                    {
                        Require(evidence.layouts.Length == 3 &&
                                evidence.layouts.Select(value => value.locale).OrderBy(value => value, StringComparer.Ordinal)
                                    .SequenceEqual(new[] { "en", "ko", "qps-long" }),
                            "locale layouts=" + string.Join(",", evidence.layouts.Select(value => value.locale).ToArray()));
                        Require(evidence.layouts.All(value => value.result == "PASS"),
                            "layout failures=" + string.Join(" | ", evidence.layouts.Select(DescribeLayout).ToArray()));
                        Require(!string.IsNullOrWhiteSpace(evidence.keyboardMeaning) &&
                                string.Equals(evidence.keyboardMeaning, evidence.gamepadMeaning, StringComparison.Ordinal),
                            "keyboard/gamepad meaning=" + evidence.keyboardMeaning + "/" + evidence.gamepadMeaning);
                        Require(evidence.localeStateFingerprints.Length == 3 &&
                                evidence.localeStateFingerprints.Distinct(StringComparer.Ordinal).Count() == 1,
                            "locale changed progress state: " + string.Join(",", evidence.localeStateFingerprints));
                        return "meaning=" + evidence.keyboardMeaning + "; layouts=" +
                               string.Join(" | ", evidence.layouts.Select(DescribeLayout).ToArray());
                    },
                    "Capture the same actual disease/search state in all locales and actuate identical actions through both synthetic input paths.",
                    "runtime disease/search HUD, canonical localization, and action input owners selected by live observation");

                Product(checks, "GWB-P05.actual_natural_trace_no_cheats", "acceptance integrity", "P0",
                    "Acceptance comes from an active live Scene component, stable IDs, structured state fingerprints, and a natural region/search/treatment trace with grant/warp/skip false",
                    delegate
                    {
                        Require(!string.IsNullOrWhiteSpace(evidence.liveObservationOwner) &&
                                !string.IsNullOrWhiteSpace(evidence.liveObservationMethod),
                            "no live Wave B observation owner: " + evidence.observationError);
                        Require(evidence.cheatFieldsObserved && !evidence.grant && !evidence.warp && !evidence.skip,
                            "grant/warp/skip fields missing or contaminated=" + evidence.cheatFieldsObserved + "/" +
                            evidence.grant + "/" + evidence.warp + "/" + evidence.skip);
                        Require(TraceHas(evidence.diseaseInteractionTrace, "region") &&
                                TraceHas(evidence.diseaseInteractionTrace, "expedition") &&
                                TraceHas(evidence.diseaseInteractionTrace, "search") &&
                                (TraceHas(evidence.diseaseInteractionTrace, "treat") || TraceHas(evidence.diseaseInteractionTrace, "mitigat")),
                            "natural interaction path incomplete: " + string.Join(" | ", evidence.diseaseInteractionTrace));
                        return DescribeDisease(evidence);
                    },
                    "Independently discover an active Scene component by returned structured surface and inspect actual trace/state values; never accept a bool result or fixture text.",
                    "runtime live Wave B observation owner selected by returned member shape, not class name");

                WriteJson("gamejam-wave-b-play-observation-evidence.json", evidence);
                Report report = WriteReport("gamejam-wave-b-play-contracts", "GameJam Wave B RED-first actual Play contracts", started, checks);
                SessionState.SetBool(PlayExitPassKey, report.infrastructureOverall == "PASS");
                SessionState.SetString(PlayMessageKey, "GameJam Wave B Play contracts: " + report.overall);
            }
            catch (Exception exception)
            {
                WritePlayInfrastructureFailure(exception);
            }
            StopPlayContracts();
        }

        private static PlayEvidence ObservePlay()
        {
            PlayEvidence evidence = new PlayEvidence
            {
                runId = RunId,
                baselineCommit = BaselineCommit,
                scene = SceneManager.GetActiveScene().path,
                discoveryPolicy = "Fresh GSN artifact for the locked search trace plus active live Scene component selected by structured Wave B return surface. Bool assertions and fixture-only methods are rejected.",
                joystickNames = Input.GetJoystickNames() ?? Array.Empty<string>()
            };

            string gsnPath = Path.Combine(EvidenceFolder, "gamejam-search-node-play-observation-evidence.json");
            if (File.Exists(gsnPath))
            {
                try
                {
                    FreshSearchEvidence search = JsonUtility.FromJson<FreshSearchEvidence>(File.ReadAllText(gsnPath, Encoding.UTF8));
                    if (search != null)
                    {
                        evidence.searchEvidenceSource = Path.GetFileName(gsnPath);
                        evidence.searchStateSequence = search.stateSequence ?? Array.Empty<string>();
                        evidence.searchInteractionTrace = search.interactionTrace ?? Array.Empty<string>();
                        evidence.knownRemainingFingerprint = search.remainingItemsFingerprint ?? string.Empty;
                        evidence.searchGrant = search.grant;
                        evidence.searchWarp = search.warp;
                        evidence.searchSkip = search.skip;
                    }
                }
                catch (Exception exception)
                {
                    evidence.observationError = "Fresh GSN evidence read failed: " + exception.Message;
                }
            }

            MonoBehaviour[] owners = UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsInactive.Exclude);
            List<string> errors = new List<string>();
            foreach (MonoBehaviour owner in owners.Where(value => value != null && value.isActiveAndEnabled))
            {
                MethodInfo[] methods = owner.GetType().GetMethods(PublicInstance)
                    .Where(IsWaveBObservationMethod)
                    .OrderByDescending(value => WaveBObservationScore(value.ReturnType))
                    .ToArray();
                foreach (MethodInfo method in methods)
                {
                    try
                    {
                        object observed = method.Invoke(owner, null);
                        if (observed == null || WaveBObservationScore(observed.GetType()) < 12) continue;
                        PopulateLiveEvidence(evidence, owner, method, observed);
                        return evidence;
                    }
                    catch (Exception exception)
                    {
                        Exception root = exception is TargetInvocationException && exception.InnerException != null
                            ? exception.InnerException
                            : exception;
                        errors.Add(owner.GetType().FullName + "." + method.Name + ": " + root.GetType().Name + " " + root.Message);
                    }
                }
            }
            evidence.observationError = errors.Count == 0
                ? "No active live Scene component exposes a structured Wave B disease/persistence observation."
                : string.Join(" | ", errors.ToArray());
            return evidence;
        }

        private static bool IsWaveBObservationMethod(MethodInfo method)
        {
            if (method == null || method.IsStatic || method.ContainsGenericParameters || method.GetParameters().Length != 0) return false;
            Type type = method.ReturnType;
            if (type == typeof(void) || type == typeof(bool) || type == typeof(string) || type.IsPrimitive || type.IsEnum) return false;
            string surface = DescribePublicSurface(type).ToLowerInvariant();
            return surface.Contains("disease") && surface.Contains("trace") &&
                   (surface.Contains("phase") || surface.Contains("state")) &&
                   (surface.Contains("worsen") || surface.Contains("severity")) &&
                   (surface.Contains("treat") || surface.Contains("mitigat"));
        }

        private static int WaveBObservationScore(Type type)
        {
            string surface = DescribePublicSurface(type).ToLowerInvariant();
            string[] tokens =
            {
                "disease", "trace", "phase", "worsen", "treat", "mitigat", "duplicatecost",
                "duplicatehazard", "cancelcontamination", "stockfingerprint", "stockgeneration",
                "forcedreturn", "keyboard", "gamepad", "layout", "grant", "warp", "skip"
            };
            return tokens.Count(token => surface.Contains(token));
        }

        private static void PopulateLiveEvidence(PlayEvidence evidence, MonoBehaviour owner, MethodInfo method, object observed)
        {
            evidence.liveObservationOwner = owner.GetType().FullName;
            evidence.liveObservationMethod = method.Name;
            evidence.liveObservationSurface = DescribePublicSurface(observed.GetType());
            evidence.observationError = ReadString(observed, "ObservationError", "Error");

            string[] liveSearchStates = ReadStrings(observed, "SearchStateSequence", "NodeStateSequence");
            string[] liveSearchTrace = ReadStrings(observed, "SearchInteractionTrace", "PersistenceTrace");
            if (liveSearchStates.Length > 0) evidence.searchStateSequence = liveSearchStates;
            if (liveSearchTrace.Length > 0) evidence.searchInteractionTrace = liveSearchTrace;
            string liveRemaining = ReadString(observed, "KnownRemainingFingerprint", "RemainingItemsFingerprint");
            if (!string.IsNullOrWhiteSpace(liveRemaining)) evidence.knownRemainingFingerprint = liveRemaining;
            evidence.stockFingerprints = ReadStrings(observed, "StockFingerprints", "GeneralStockFingerprints");
            evidence.stockGenerationEvents = ReadStrings(observed, "StockGenerationEvents", "GenerationEvents");
            evidence.diseaseId = ReadString(observed, "DiseaseId", "DiseaseStableId", "HazardId");
            evidence.diseasePhaseSequence = ReadStrings(observed, "DiseasePhaseSequence", "DiseaseStateSequence", "PhaseSequence");
            evidence.diseaseInteractionTrace = ReadStrings(observed, "DiseaseInteractionTrace", "InteractionTrace");
            evidence.diseaseStateFingerprints = ReadStrings(observed, "DiseaseStateFingerprints", "StateFingerprints");
            evidence.exposureApplyCount = ReadInt(observed, -1, "ExposureApplyCount", "ExposureCount");
            evidence.effectApplyCount = ReadInt(observed, -1, "EffectApplyCount", "EffectCount");
            evidence.worsenApplyCount = ReadInt(observed, -1, "WorsenApplyCount", "WorsenCount");
            evidence.treatmentCostCount = ReadInt(observed, -1, "TreatmentCostCount", "MitigationCostCount");
            evidence.duplicateCostDelta = ReadInt(observed, int.MinValue, "DuplicateCostDelta");
            evidence.duplicateHazardDelta = ReadInt(observed, int.MinValue, "DuplicateHazardDelta", "DuplicateExposureDelta");
            evidence.cancelContaminationDelta = ReadInt(observed, int.MinValue, "CancelContaminationDelta", "CancelStateDelta");
            evidence.grant = ReadBool(observed, "Grant", "UsedGrant");
            evidence.warp = ReadBool(observed, "Warp", "UsedWarp");
            evidence.skip = ReadBool(observed, "Skip", "UsedSkip");
            evidence.cheatFieldsObserved = HasMember(observed.GetType(), "Grant", "UsedGrant") &&
                                           HasMember(observed.GetType(), "Warp", "UsedWarp") &&
                                           HasMember(observed.GetType(), "Skip", "UsedSkip");
            evidence.keyboardMeaning = ReadString(observed, "KeyboardMeaning", "KeyboardMouseMeaning");
            evidence.gamepadMeaning = ReadString(observed, "GamepadMeaning", "SyntheticGamepadMeaning");
            evidence.localeStateFingerprints = ReadStrings(observed, "LocaleStateFingerprints", "LocalizedStateFingerprints");
            evidence.layouts = ReadLayouts(observed);
        }

        private static LayoutEvidence[] ReadLayouts(object observed)
        {
            object value = GetMember(observed, "Layouts", "LayoutObservations", "LocalizedLayouts");
            if (!(value is IEnumerable enumerable) || value is string) return Array.Empty<LayoutEvidence>();
            List<LayoutEvidence> output = new List<LayoutEvidence>();
            foreach (object item in enumerable)
            {
                if (item == null) continue;
                LayoutEvidence layout = new LayoutEvidence
                {
                    locale = ReadString(item, "Locale", "LocaleCode").ToLowerInvariant(),
                    screenshot = ResolveEvidencePath(ReadString(item, "Screenshot", "Capture", "Path")),
                    overflowCount = ReadInt(item, -1, "OverflowCount", "TmpOverflowCount"),
                    offscreenCount = ReadInt(item, -1, "OffscreenCount", "OffscreenTextCount"),
                    playerClear = ReadBool(item, "PlayerClear", "PlayerNotOccluded"),
                    walkingBandClear = ReadBool(item, "WalkingBandClear", "RequiredPathClear")
                };
                string failure = ValidateLayout(layout);
                layout.result = string.IsNullOrEmpty(failure) ? "PASS" : "FAIL";
                layout.failureReason = failure;
                output.Add(layout);
            }
            return output.ToArray();
        }

        private static string ValidateLayout(LayoutEvidence layout)
        {
            List<string> failures = new List<string>();
            if (!new[] { "ko", "en", "qps-long" }.Contains(layout.locale)) failures.Add("locale");
            if (string.IsNullOrWhiteSpace(layout.screenshot) || !File.Exists(layout.screenshot)) failures.Add("capture-missing");
            else
            {
                string full = Path.GetFullPath(layout.screenshot);
                if (!full.StartsWith(EvidenceFolder + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase)) failures.Add("capture-outside-run");
                try
                {
                    Texture2D texture = new Texture2D(2, 2);
                    if (!texture.LoadImage(File.ReadAllBytes(full))) failures.Add("capture-invalid");
                    else
                    {
                        layout.screenWidth = texture.width;
                        layout.screenHeight = texture.height;
                        if (texture.width != 1280 || texture.height != 800) failures.Add("resolution");
                    }
                    UnityEngine.Object.DestroyImmediate(texture);
                }
                catch { failures.Add("capture-read"); }
            }
            if (layout.overflowCount != 0) failures.Add("overflow=" + layout.overflowCount);
            if (layout.offscreenCount != 0) failures.Add("offscreen=" + layout.offscreenCount);
            if (!layout.playerClear) failures.Add("player-occluded");
            if (!layout.walkingBandClear) failures.Add("walking-band-occluded");
            return string.Join(",", failures.ToArray());
        }

        private static CatalogEvidence DiscoverCatalog(Assembly runtime)
        {
            CatalogCandidate best = new CatalogCandidate();
            foreach (Type type in SafeTypes(runtime))
            {
                List<object> values = new List<object>();
                foreach (FieldInfo field in type.GetFields(PublicStatic))
                {
                    try
                    {
                        object value = field.GetValue(null);
                        if (IsStructuredRoot(value)) values.Add(value);
                    }
                    catch { }
                }
                foreach (PropertyInfo property in type.GetProperties(PublicStatic).Where(value => value.GetIndexParameters().Length == 0))
                {
                    try
                    {
                        object value = property.GetValue(null, null);
                        if (IsStructuredRoot(value)) values.Add(value);
                    }
                    catch { }
                }
                if (values.Count == 0) continue;
                CatalogCandidate candidate = new CatalogCandidate { Owner = type.FullName };
                AuditGraph(values.ToArray(), candidate, type.FullName, 0, new HashSet<object>(new ReferenceComparer()));
                if (CatalogScore(candidate) > CatalogScore(best)) best = candidate;
            }

            int bucketTotal = best.ResourceBuckets.Sum(value => value.Units);
            ResourceBucket exact = best.ResourceBuckets.FirstOrDefault(value => value.Units == ExpectedGeneralUnits);
            int units = exact != null ? exact.Units : (bucketTotal > 0 ? bucketTotal : best.LootUnits);
            int entries = exact != null ? exact.Entries : (bucketTotal > 0 ? best.ResourceBuckets.Sum(value => value.Entries) : best.LootEntries);
            return new CatalogEvidence
            {
                owner = best.Owner,
                regionIds = best.RegionIds.OrderBy(value => value, StringComparer.Ordinal).ToArray(),
                archetypeIds = best.ArchetypeIds.OrderBy(value => value, StringComparer.Ordinal).ToArray(),
                instanceIds = best.InstanceIds.OrderBy(value => value, StringComparer.Ordinal).ToArray(),
                legacyNodeIds = best.LegacyNodeIds.OrderBy(value => value, StringComparer.Ordinal).ToArray(),
                finiteGeneralResourceUnits = units,
                finiteResourceEntryCount = entries,
                finiteResourceSources = best.ResourceBuckets.Select(value => value.Path + "=" + value.Units).ToArray()
            };
        }

        private static void AuditGraph(object value, CatalogCandidate audit, string path, int depth, HashSet<object> visited)
        {
            if (value == null || depth > 8) return;
            Type type = value.GetType();
            if (value is string text)
            {
                CollectStableId(text, audit);
                return;
            }
            if (type.IsPrimitive || type.IsEnum || value is decimal || value is DateTime) return;
            if (value is UnityEngine.Object) return;
            if (!type.IsValueType && !visited.Add(value)) return;

            if (value is IDictionary dictionary)
            {
                ResourceBucket bucket = new ResourceBucket { Path = path };
                foreach (DictionaryEntry entry in dictionary)
                {
                    string key = Convert.ToString(entry.Key) ?? string.Empty;
                    CollectStableId(key, audit);
                    if (IsResourceId(key) && TryPositiveInt(entry.Value, out int amount))
                    {
                        bucket.Units += amount;
                        bucket.Entries += 1;
                    }
                    AuditGraph(entry.Value, audit, path + "[" + key + "]", depth + 1, visited);
                }
                if (bucket.Entries > 0 && ContainsAny(path.ToLowerInvariant(), "finite", "yield", "stock", "resource"))
                    audit.ResourceBuckets.Add(bucket);
                return;
            }

            if (value is IEnumerable enumerable)
            {
                int index = 0;
                foreach (object item in enumerable)
                {
                    AuditGraph(item, audit, path + "[" + index + "]", depth + 1, visited);
                    index += 1;
                    if (index > 4096) break;
                }
                return;
            }

            string resource = ReadString(value, "ResourceId", "StableResourceId", "Resource");
            int amountValue = ReadInt(value, 0, "Amount", "Count", "Units", "Quantity");
            string protectedId = ReadString(value, "ProtectedPartId", "KeyPartId", "PartId");
            if (amountValue > 0 && string.IsNullOrWhiteSpace(protectedId) &&
                !string.IsNullOrWhiteSpace(resource) &&
                ContainsAny(path.ToLowerInvariant(), "content", "loot", "remaining", "stock", "yield"))
            {
                audit.LootUnits += amountValue;
                audit.LootEntries += 1;
            }

            foreach (FieldInfo field in type.GetFields(PublicInstance).OrderBy(item => item.Name, StringComparer.Ordinal))
            {
                object member;
                try { member = field.GetValue(value); } catch { continue; }
                if (member is string id) CollectStableId(id, audit);
                AuditGraph(member, audit, path + "." + field.Name, depth + 1, visited);
            }
            foreach (PropertyInfo property in type.GetProperties(PublicInstance)
                         .Where(item => item.GetIndexParameters().Length == 0 && item.CanRead)
                         .OrderBy(item => item.Name, StringComparer.Ordinal))
            {
                object member;
                try { member = property.GetValue(value, null); } catch { continue; }
                if (member is string id) CollectStableId(id, audit);
                AuditGraph(member, audit, path + "." + property.Name, depth + 1, visited);
            }
        }

        private static void CollectStableId(string value, CatalogCandidate audit)
        {
            if (string.IsNullOrWhiteSpace(value)) return;
            if (value.StartsWith("region.", StringComparison.Ordinal)) audit.RegionIds.Add(value);
            else if (value.StartsWith("node.archetype.", StringComparison.Ordinal)) audit.ArchetypeIds.Add(value);
            else if (value.StartsWith("node.instance.", StringComparison.Ordinal)) audit.InstanceIds.Add(value);
            else if (value.StartsWith("node.", StringComparison.Ordinal) &&
                     value.IndexOf(".loot.", StringComparison.Ordinal) < 0 &&
                     value.IndexOf(".protected.", StringComparison.Ordinal) < 0)
                audit.LegacyNodeIds.Add(value);
        }

        private static int CatalogScore(CatalogCandidate candidate)
        {
            int expectedRegions = candidate.RegionIds.Count(value => ExpectedRegionIds.Contains(value));
            return expectedRegions * 100000 + candidate.ArchetypeIds.Count * 1000 +
                   candidate.InstanceIds.Count * 10 + candidate.LegacyNodeIds.Count;
        }

        private static GenerationEvidence DiscoverGeneration(Assembly runtime)
        {
            GenerationEvidence evidence = new GenerationEvidence();
            List<string> errors = new List<string>();
            foreach (Type type in SafeTypes(runtime))
            {
                foreach (MethodInfo method in type.GetMethods(PublicStatic))
                {
                    ParameterInfo[] parameters = method.GetParameters();
                    if (method.ContainsGenericParameters || method.ReturnType == typeof(void) ||
                        method.ReturnType == typeof(bool) || method.ReturnType == typeof(string) ||
                        parameters.Length < 2 || parameters.Length > 6) continue;
                    if (!parameters.Any(value => ContainsAny(value.Name.ToLowerInvariant(), "seed")) ||
                        !parameters.Any(value => ContainsAny(value.Name.ToLowerInvariant(), "revision"))) continue;
                    try
                    {
                        object[] firstArgs = BuildGenerationArguments(parameters, 72017);
                        object[] alternateArgs = BuildGenerationArguments(parameters, 72018);
                        object first = method.Invoke(null, firstArgs);
                        object repeat = method.Invoke(null, firstArgs);
                        object alternate = method.Invoke(null, alternateArgs);
                        if (first == null || repeat == null || alternate == null) continue;
                        string firstCanonical = Canonicalize(first);
                        string repeatCanonical = Canonicalize(repeat);
                        string alternateCanonical = Canonicalize(alternate);
                        CatalogCandidate firstAudit = new CatalogCandidate();
                        CatalogCandidate alternateAudit = new CatalogCandidate();
                        AuditGraph(first, firstAudit, "generated", 0, new HashSet<object>(new ReferenceComparer()));
                        AuditGraph(alternate, alternateAudit, "generated", 0, new HashSet<object>(new ReferenceComparer()));
                        if (firstAudit.InstanceIds.Count < ExpectedInstanceCount) continue;
                        string surface = DescribePublicSurface(first.GetType()).ToLowerInvariant() + " " + CanonicalMemberNames(first);
                        evidence.owner = type.FullName + "." + method.Name;
                        evidence.methodSurface = DescribeMethod(method) + " -> " + DescribePublicSurface(first.GetType());
                        evidence.sameSeedRevisionByteEqual = string.Equals(firstCanonical, repeatCanonical, StringComparison.Ordinal);
                        evidence.differentSeedVaries = !string.Equals(firstCanonical, alternateCanonical, StringComparison.Ordinal);
                        evidence.stableIdsPreservedAcrossSeeds = firstAudit.RegionIds.SetEquals(alternateAudit.RegionIds) &&
                                                                  firstAudit.ArchetypeIds.SetEquals(alternateAudit.ArchetypeIds) &&
                                                                  firstAudit.InstanceIds.SetEquals(alternateAudit.InstanceIds);
                        evidence.revisionsStored = surface.Contains("contractrevision") && surface.Contains("loottablerevision");
                        evidence.firstSha256 = Sha256(firstCanonical);
                        evidence.repeatSha256 = Sha256(repeatCanonical);
                        evidence.alternateSha256 = Sha256(alternateCanonical);
                        return evidence;
                    }
                    catch (Exception exception)
                    {
                        Exception root = exception is TargetInvocationException && exception.InnerException != null
                            ? exception.InnerException
                            : exception;
                        errors.Add(type.FullName + "." + method.Name + ": " + root.Message);
                    }
                }
            }
            evidence.error = errors.Count == 0
                ? "No public structured method accepts both seed and revision and returns 42 stable instances."
                : string.Join(" | ", errors.Take(8).ToArray());
            return evidence;
        }

        private static object[] BuildGenerationArguments(ParameterInfo[] parameters, int seed)
        {
            object[] output = new object[parameters.Length];
            for (int index = 0; index < parameters.Length; index += 1)
            {
                ParameterInfo parameter = parameters[index];
                string name = (parameter.Name ?? string.Empty).ToLowerInvariant();
                Type type = parameter.ParameterType;
                if (type == typeof(int)) output[index] = name.Contains("seed") ? seed : (name.Contains("revision") ? 1 : 0);
                else if (type == typeof(long)) output[index] = name.Contains("seed") ? (long)seed : (name.Contains("revision") ? 1L : 0L);
                else if (type == typeof(string)) output[index] = name.Contains("seed") ? seed.ToString() : (name.Contains("revision") ? "1" : string.Empty);
                else if (type == typeof(bool)) output[index] = name.Contains("new") || name.Contains("fresh");
                else if (type.IsEnum) output[index] = Enum.GetValues(type).GetValue(0);
                else if (parameter.HasDefaultValue) output[index] = parameter.DefaultValue;
                else if (!type.IsValueType) output[index] = null;
                else output[index] = Activator.CreateInstance(type);
            }
            return output;
        }

        private static string DiscoverPersistenceSurface(Assembly runtime)
        {
            List<string> rows = new List<string>();
            foreach (Type type in SafeTypes(runtime))
            {
                string members = DescribePublicSurface(type).ToLowerInvariant();
                string methods = string.Join(",", type.GetMethods(PublicInstance | PublicStatic)
                    .Where(method => method.DeclaringType == type)
                    .Select(method => method.Name.ToLowerInvariant()).Distinct().OrderBy(value => value, StringComparer.Ordinal).ToArray());
                string combined = members + "," + methods;
                if (ContainsAny(combined, "snapshot", "revision", "stock", "newgame", "barrier", "permanenthazard", "knownremaining"))
                    rows.Add(type.FullName + "{" + combined + "}");
            }
            return string.Join(" | ", rows.Take(24).ToArray());
        }

        private static string AuditLocalization(out bool passed)
        {
            string path = Path.GetFullPath(Path.Combine(Application.dataPath, "_Project", "Scripts", "Localization", "PrototypeStrings.tsv"));
            if (!File.Exists(path))
            {
                passed = false;
                return "canonical TSV missing: " + path;
            }
            string[] lines = File.ReadAllLines(path, Encoding.UTF8).Where(value => !string.IsNullOrWhiteSpace(value)).ToArray();
            if (lines.Length < 2)
            {
                passed = false;
                return "canonical TSV has no rows";
            }
            string[] header = lines[0].Split('\t');
            int keyIndex = Array.FindIndex(header, value => string.Equals(value.Trim(), "key", StringComparison.OrdinalIgnoreCase));
            int koIndex = Array.FindIndex(header, value => string.Equals(value.Trim(), "ko", StringComparison.OrdinalIgnoreCase));
            int enIndex = Array.FindIndex(header, value => string.Equals(value.Trim(), "en", StringComparison.OrdinalIgnoreCase));
            int qpsIndex = Array.FindIndex(header, value => string.Equals(value.Trim(), "qps-long", StringComparison.OrdinalIgnoreCase));
            if (keyIndex < 0 || koIndex < 0 || enIndex < 0 || qpsIndex < 0)
            {
                passed = false;
                return "required key/ko/en/qps-long columns are missing";
            }
            List<string[]> rows = lines.Skip(1).Select(value => value.Split('\t')).ToList();
            string[][] groups =
            {
                new[] { "known-remaining", "known_remaining", "remaining" },
                new[] { "barrier-broken", "barrier_broken" },
                new[] { "hazard-removed", "hazard_removed", "removed-hazard" },
                new[] { "disease.telegraph", "disease_telegraph", "disease.warning" },
                new[] { "disease.exposure", "disease_exposure", "disease.exposed" },
                new[] { "disease.effect", "disease_effect", "disease.symptom" },
                new[] { "disease.worsen", "disease_worsen", "disease.severity" },
                new[] { "disease.mitigat", "disease.treat", "disease_treat" }
            };
            List<string> missing = new List<string>();
            foreach (string[] group in groups)
            {
                string[] row = rows.FirstOrDefault(value => value.Length > Math.Max(Math.Max(keyIndex, koIndex), Math.Max(enIndex, qpsIndex)) &&
                    group.Any(alias => value[keyIndex].IndexOf(alias, StringComparison.OrdinalIgnoreCase) >= 0));
                if (row == null || string.IsNullOrWhiteSpace(row[koIndex]) || string.IsNullOrWhiteSpace(row[enIndex]) || string.IsNullOrWhiteSpace(row[qpsIndex]))
                    missing.Add(string.Join("/", group));
            }
            passed = missing.Count == 0;
            return "rows=" + rows.Count + "; missing=" + string.Join(",", missing.ToArray());
        }

        private static string Canonicalize(object value)
        {
            StringBuilder output = new StringBuilder();
            Canonicalize(value, output, 0, new HashSet<object>(new ReferenceComparer()));
            return output.ToString();
        }

        private static void Canonicalize(object value, StringBuilder output, int depth, HashSet<object> visited)
        {
            if (value == null) { output.Append("null"); return; }
            if (depth > 12) { output.Append("#depth"); return; }
            Type type = value.GetType();
            if (value is string text) { output.Append('"').Append(text.Replace("\\", "\\\\").Replace("\"", "\\\"")).Append('"'); return; }
            if (type.IsPrimitive || type.IsEnum || value is decimal) { output.Append(Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture)); return; }
            if (!type.IsValueType && !visited.Add(value)) { output.Append("#ref"); return; }
            if (value is IDictionary dictionary)
            {
                output.Append('{');
                List<DictionaryEntry> entries = dictionary.Cast<DictionaryEntry>()
                    .OrderBy(entry => Convert.ToString(entry.Key), StringComparer.Ordinal).ToList();
                foreach (DictionaryEntry entry in entries)
                {
                    output.Append(Convert.ToString(entry.Key)).Append(':');
                    Canonicalize(entry.Value, output, depth + 1, visited);
                    output.Append(';');
                }
                output.Append('}');
                return;
            }
            if (value is IEnumerable enumerable)
            {
                output.Append('[');
                foreach (object item in enumerable) { Canonicalize(item, output, depth + 1, visited); output.Append(';'); }
                output.Append(']');
                return;
            }
            output.Append(type.FullName).Append('{');
            foreach (MemberInfo member in PublicDataMembers(type))
            {
                object memberValue;
                try { memberValue = member is FieldInfo field ? field.GetValue(value) : ((PropertyInfo)member).GetValue(value, null); }
                catch { continue; }
                output.Append(member.Name).Append('=');
                Canonicalize(memberValue, output, depth + 1, visited);
                output.Append(';');
            }
            output.Append('}');
        }

        private static IEnumerable<MemberInfo> PublicDataMembers(Type type)
        {
            return type.GetFields(PublicInstance).Cast<MemberInfo>()
                .Concat(type.GetProperties(PublicInstance).Where(value => value.CanRead && value.GetIndexParameters().Length == 0))
                .OrderBy(value => value.Name, StringComparer.Ordinal);
        }

        private static string CanonicalMemberNames(object value)
        {
            HashSet<string> names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            CollectMemberNames(value, names, 0, new HashSet<object>(new ReferenceComparer()));
            return string.Join(",", names.OrderBy(item => item, StringComparer.Ordinal).ToArray());
        }

        private static void CollectMemberNames(object value, HashSet<string> names, int depth, HashSet<object> visited)
        {
            if (value == null || depth > 8) return;
            Type type = value.GetType();
            if (value is string || type.IsPrimitive || type.IsEnum || value is decimal || value is UnityEngine.Object) return;
            if (!type.IsValueType && !visited.Add(value)) return;
            if (value is IEnumerable enumerable)
            {
                foreach (object item in enumerable) CollectMemberNames(item, names, depth + 1, visited);
                return;
            }
            foreach (MemberInfo member in PublicDataMembers(type))
            {
                names.Add(member.Name.ToLowerInvariant());
                object child;
                try { child = member is FieldInfo field ? field.GetValue(value) : ((PropertyInfo)member).GetValue(value, null); }
                catch { continue; }
                CollectMemberNames(child, names, depth + 1, visited);
            }
        }

        private static string Sha256(string text)
        {
            using (System.Security.Cryptography.SHA256 sha = System.Security.Cryptography.SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(text ?? string.Empty));
                return BitConverter.ToString(hash).Replace("-", string.Empty).ToLowerInvariant();
            }
        }

        private static bool DiseaseSequencePasses(IEnumerable<string> sequence)
        {
            string[] values = (sequence ?? Array.Empty<string>()).Select(value => (value ?? string.Empty).ToLowerInvariant()).ToArray();
            string[][] phases =
            {
                new[] { "telegraph", "warning" },
                new[] { "exposure", "exposed" },
                new[] { "effect", "symptom", "active" },
                new[] { "worsen", "aggravat", "severity" },
                new[] { "mitigat", "treat", "treated" }
            };
            int cursor = 0;
            foreach (string[] phase in phases)
            {
                int found = -1;
                for (int index = cursor; index < values.Length; index += 1)
                {
                    if (phase.Any(alias => values[index].Contains(alias))) { found = index; break; }
                }
                if (found < 0) return false;
                cursor = found + 1;
            }
            return true;
        }

        private static bool SequenceHas(IEnumerable<string> sequence, params string[] tokens)
        {
            string combined = string.Join(" ", sequence ?? Array.Empty<string>()).ToLowerInvariant();
            return tokens.All(combined.Contains);
        }

        private static bool TraceHas(IEnumerable<string> trace, params string[] tokens)
        {
            return (trace ?? Array.Empty<string>()).Any(value => tokens.All(token =>
                (value ?? string.Empty).IndexOf(token, StringComparison.OrdinalIgnoreCase) >= 0));
        }

        private static bool IsStableDiseaseId(string value)
        {
            return !string.IsNullOrWhiteSpace(value) &&
                   (value.StartsWith("disease.", StringComparison.Ordinal) || value.StartsWith("hazard.disease", StringComparison.Ordinal));
        }

        private static bool IsStructuredRoot(object value)
        {
            if (value == null || value is string || value is UnityEngine.Object) return false;
            Type type = value.GetType();
            return !type.IsPrimitive && !type.IsEnum;
        }

        private static bool IsResourceId(string value)
        {
            return !string.IsNullOrWhiteSpace(value) && value.StartsWith("resource.", StringComparison.Ordinal);
        }

        private static bool TryPositiveInt(object value, out int amount)
        {
            try { amount = Convert.ToInt32(value); return amount > 0; }
            catch { amount = 0; return false; }
        }

        private static Type[] SafeTypes(Assembly assembly)
        {
            try { return assembly.GetTypes(); }
            catch (ReflectionTypeLoadException exception) { return exception.Types.Where(value => value != null).ToArray(); }
        }

        private static string DescribeMethod(MethodInfo method)
        {
            return method.DeclaringType.FullName + "." + method.Name + "(" +
                   string.Join(",", method.GetParameters().Select(value => value.ParameterType.Name + " " + value.Name).ToArray()) + ")";
        }

        private static string DescribePublicSurface(Type type)
        {
            if (type == null) return string.Empty;
            return string.Join(",", type.GetFields(PublicInstance).Select(value => value.Name)
                .Concat(type.GetProperties(PublicInstance).Where(value => value.GetIndexParameters().Length == 0).Select(value => value.Name))
                .Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(value => value, StringComparer.OrdinalIgnoreCase).ToArray());
        }

        private static bool HasMember(Type type, params string[] aliases)
        {
            return aliases.Any(alias => type.GetFields(PublicInstance).Any(value => string.Equals(value.Name, alias, StringComparison.OrdinalIgnoreCase)) ||
                                        type.GetProperties(PublicInstance).Any(value => string.Equals(value.Name, alias, StringComparison.OrdinalIgnoreCase)));
        }

        private static object GetMember(object owner, params string[] aliases)
        {
            if (owner == null) return null;
            Type type = owner.GetType();
            foreach (string alias in aliases)
            {
                FieldInfo field = type.GetFields(PublicInstance).FirstOrDefault(value => string.Equals(value.Name, alias, StringComparison.OrdinalIgnoreCase));
                if (field != null) { try { return field.GetValue(owner); } catch { } }
                PropertyInfo property = type.GetProperties(PublicInstance).FirstOrDefault(value =>
                    value.GetIndexParameters().Length == 0 && string.Equals(value.Name, alias, StringComparison.OrdinalIgnoreCase));
                if (property != null) { try { return property.GetValue(owner, null); } catch { } }
            }
            return null;
        }

        private static string ReadString(object owner, params string[] aliases)
        {
            object value = GetMember(owner, aliases);
            return value == null ? string.Empty : Convert.ToString(value) ?? string.Empty;
        }

        private static string[] ReadStrings(object owner, params string[] aliases)
        {
            object value = GetMember(owner, aliases);
            if (!(value is IEnumerable enumerable) || value is string) return Array.Empty<string>();
            return enumerable.Cast<object>().Where(item => item != null).Select(item => Convert.ToString(item) ?? string.Empty).ToArray();
        }

        private static int ReadInt(object owner, int fallback, params string[] aliases)
        {
            object value = GetMember(owner, aliases);
            if (value == null) return fallback;
            try { return Convert.ToInt32(value); } catch { return fallback; }
        }

        private static bool ReadBool(object owner, params string[] aliases)
        {
            object value = GetMember(owner, aliases);
            if (value == null) return false;
            try { return Convert.ToBoolean(value); } catch { return false; }
        }

        private static string ResolveEvidencePath(string value)
        {
            if (string.IsNullOrWhiteSpace(value)) return string.Empty;
            return Path.GetFullPath(Path.IsPathRooted(value) ? value : Path.Combine(EvidenceFolder, value));
        }

        private static bool ContainsAny(string source, params string[] tokens)
        {
            return tokens.Any(source.Contains);
        }

        private static string DescribeCatalog(CatalogEvidence value)
        {
            return "owner=" + value.owner + "; regions=" + value.regionIds.Length +
                   "; archetypes=" + value.archetypeIds.Length + "; instances=" + value.instanceIds.Length +
                   "; legacyNodes=" + value.legacyNodeIds.Length + "; generalUnits=" + value.finiteGeneralResourceUnits +
                   "; sources=" + string.Join(" | ", value.finiteResourceSources);
        }

        private static string DescribeDisease(PlayEvidence value)
        {
            return "owner=" + value.liveObservationOwner + "; method=" + value.liveObservationMethod +
                   "; disease=" + value.diseaseId + "; phases=" + string.Join(">", value.diseasePhaseSequence) +
                   "; counts=" + value.exposureApplyCount + "/" + value.effectApplyCount + "/" +
                   value.worsenApplyCount + "/" + value.treatmentCostCount + "; error=" + value.observationError;
        }

        private static string DescribeLayout(LayoutEvidence value)
        {
            return value.locale + "=" + value.screenWidth + "x" + value.screenHeight +
                   "; overflow/offscreen=" + value.overflowCount + "/" + value.offscreenCount +
                   "; player/path=" + value.playerClear + "/" + value.walkingBandClear +
                   "; result=" + value.result + "; reason=" + value.failureReason;
        }

        private static void Product(List<Check> checks, string id, string matrix, string severity, string expected,
            Func<string> action, string reproduction, string recommendedFiles)
        {
            try
            {
                string actual = action();
                checks.Add(NewCheck(id, matrix, "PASS", "NONE", severity, expected, actual, reproduction, recommendedFiles));
            }
            catch (Exception exception)
            {
                string status = IsRedBaseline ? "EXPECTED_GAP" : "FAIL";
                string classification = IsRedBaseline ? "PRODUCT_EXPECTED_GAP" : "PRODUCT_REGRESSION";
                checks.Add(NewCheck(id, matrix, status, classification, severity, expected,
                    exception.GetType().Name + ": " + exception.Message, reproduction, recommendedFiles));
            }
        }

        private static void Infrastructure(List<Check> checks, string id, string matrix, string severity, string expected,
            Func<string> action, string reproduction, string recommendedFiles)
        {
            try
            {
                checks.Add(NewCheck(id, matrix, "PASS", "NONE", severity, expected, action(), reproduction, recommendedFiles));
            }
            catch (Exception exception)
            {
                checks.Add(NewCheck(id, matrix, "INFRA_FAIL", "INFRASTRUCTURE", severity, expected,
                    exception.GetType().Name + ": " + exception.Message, reproduction, recommendedFiles));
            }
        }

        private static Check NewCheck(string id, string matrix, string status, string classification, string severity,
            string expected, string actual, string reproduction, string recommendedFiles)
        {
            return new Check
            {
                id = id,
                matrix = matrix,
                status = status,
                classification = classification,
                severity = severity,
                expected = expected,
                actual = actual,
                reproduction = reproduction,
                recommendedFiles = recommendedFiles
            };
        }

        private static Report WriteReport(string stem, string title, DateTime started, List<Check> checks)
        {
            Report report = new Report
            {
                title = title,
                runId = RunId,
                baselineCommit = BaselineCommit,
                unityVersion = Application.unityVersion,
                startedUtc = started.ToString("O"),
                completedUtc = DateTime.UtcNow.ToString("O"),
                passed = checks.Count(value => value.status == "PASS"),
                expectedGaps = checks.Count(value => value.status == "EXPECTED_GAP"),
                productFailed = checks.Count(value => value.status == "FAIL"),
                infrastructureFailed = checks.Count(value => value.status == "INFRA_FAIL"),
                unverified = checks.Count(value => value.status == "UNVERIFIED"),
                notReady = checks.Count(value => value.status == "NOT_READY"),
                greenCompletionCondition = "Wave B product checks are all PASS from actual structured Edit/Play evidence while GSN 15/15, Wave 19 21/21, Wave 20 16/16, compile/build/smoke/Addressables/firewall remain GREEN.",
                checks = checks.ToArray()
            };
            report.infrastructureOverall = report.infrastructureFailed == 0 ? "PASS" : "FAIL";
            report.productOverall = report.productFailed > 0 ? "FAIL" : (report.expectedGaps > 0 ? "RED_EXPECTED_GAP" : "PASS");
            report.overall = report.infrastructureOverall == "FAIL" ? "FAIL" : (report.productOverall == "PASS" ? "GREEN" : "RED");
            WriteJson(stem + ".json", report);
            string[] lines = new[]
            {
                title,
                "Run ID: " + RunId,
                "Baseline: " + BaselineCommit,
                "Unity: " + Application.unityVersion,
                "Overall/Product/Infrastructure: " + report.overall + "/" + report.productOverall + "/" + report.infrastructureOverall,
                "PASS/EXPECTED_GAP/FAIL/INFRA_FAIL: " + report.passed + "/" + report.expectedGaps + "/" + report.productFailed + "/" + report.infrastructureFailed
            }.Concat(checks.Select(value => value.id + " | " + value.status + " | " + value.classification + " | " + value.actual)).ToArray();
            File.WriteAllText(Path.Combine(EvidenceFolder, stem + ".txt"), string.Join(Environment.NewLine, lines) + Environment.NewLine, Utf8NoBom);
            return report;
        }

        private static void WriteJson(string fileName, object value)
        {
            Directory.CreateDirectory(EvidenceFolder);
            File.WriteAllText(Path.Combine(EvidenceFolder, fileName), JsonUtility.ToJson(value, true) + Environment.NewLine, Utf8NoBom);
        }

        private static void WritePlayInfrastructureFailure(Exception exception)
        {
            List<Check> checks = new List<Check>
            {
                NewCheck("GWB-I02.play_runner", "Play infrastructure", "INFRA_FAIL", "INFRASTRUCTURE", "P0",
                    "Play runner emits a fresh structured report", exception.GetType().Name + ": " + exception.Message,
                    "Run the single PowerShell entry point outside the sandbox and inspect the isolated Unity log.",
                    "Assets/Editor/ParallelQA/GameJamWaveBRedFirstGateRunner.cs")
            };
            WriteReport("gamejam-wave-b-play-contracts", "GameJam Wave B RED-first actual Play contracts", DateTime.UtcNow, checks);
            SessionState.SetBool(PlayExitPassKey, false);
            SessionState.SetString(PlayMessageKey, "INFRA_FAIL: " + exception);
        }

        private static void Require(bool condition, string message)
        {
            if (!condition) throw new InvalidOperationException(message);
        }

        private static string Sanitize(string value)
        {
            return new string(value.Select(character => char.IsLetterOrDigit(character) || character == '-' || character == '_' ? character : '_').ToArray());
        }

        private static void StopPlayContracts()
        {
            if (EditorApplication.isPlaying) EditorApplication.isPlaying = false;
        }

        private static void FinishPlayContracts()
        {
            EditorApplication.playModeStateChanged -= OnPlayModeStateChanged;
            if (playTickAttached) { EditorApplication.update -= PlayTick; playTickAttached = false; }
            bool passed = SessionState.GetBool(PlayExitPassKey, false);
            string message = SessionState.GetString(PlayMessageKey, "INFRA_FAIL: missing GameJam Wave B Play result");
            SessionState.EraseBool(PlayRunningKey);
            SessionState.EraseBool(PlayExitPassKey);
            SessionState.EraseString(PlayMessageKey);
            Debug.Log("[ParallelQA] " + message);
            EditorApplication.Exit(passed ? 0 : 1);
        }
    }
}
